/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.telas;
import com.mycompany.sistemagestaodiscente.*;
/**
Kaio de Oliveira e Sousa(202165080AC)
Filipe de Lima Namorato(202165035AB)
Gustavo Silva Ribeiro (202165057AC)
 */
public class homeAdmin extends javax.swing.JFrame {
    
    /**
     * Creates new form homeAdmin
     * @param administrador
     */
    public homeAdmin() {
       
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        panelAdmin = new javax.swing.JPanel();
        menuAdmin = new javax.swing.JMenuBar();
        CadastroD = new javax.swing.JMenu();
        CadastroA = new javax.swing.JMenuItem();
        CadastroDisc = new javax.swing.JMenuItem();
        CadastroP = new javax.swing.JMenuItem();
        CadastroT = new javax.swing.JMenuItem();
        menuAtribAdmin = new javax.swing.JMenu();
        AtribuirTA = new javax.swing.JMenuItem();
        AtribuirTP = new javax.swing.JMenuItem();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelAdmin.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        CadastroD.setText("Cadastrar");
        CadastroD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroDActionPerformed(evt);
            }
        });

        CadastroA.setText("Cadastrar Aluno");
        CadastroA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroAActionPerformed(evt);
            }
        });
        CadastroD.add(CadastroA);

        CadastroDisc.setText("Cadastrar Disciplina");
        CadastroDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroDiscActionPerformed(evt);
            }
        });
        CadastroD.add(CadastroDisc);

        CadastroP.setText("Cadastrar Professor");
        CadastroP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroPActionPerformed(evt);
            }
        });
        CadastroD.add(CadastroP);

        CadastroT.setText("Cadastrar Turma");
        CadastroT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroTActionPerformed(evt);
            }
        });
        CadastroD.add(CadastroT);

        menuAdmin.add(CadastroD);

        menuAtribAdmin.setText("Atribuir");

        AtribuirTA.setText("Atribuir Aluno a Turma ");
        AtribuirTA.setActionCommand("Atribuir Aluno a Turma");
        AtribuirTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtribuirTAActionPerformed(evt);
            }
        });
        menuAtribAdmin.add(AtribuirTA);

        AtribuirTP.setText("Atribuir Turma a Professor");
        AtribuirTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtribuirTPActionPerformed(evt);
            }
        });
        menuAtribAdmin.add(AtribuirTP);

        menuAdmin.add(menuAtribAdmin);

        setJMenuBar(menuAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroPActionPerformed
        cadastrarProfessor cProfessor = new cadastrarProfessor();
        cProfessor.setVisible(true);
    }//GEN-LAST:event_CadastroPActionPerformed
    
    private void CadastroAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroAActionPerformed
        cadastrarAluno cAluno = new cadastrarAluno();
        cAluno.setVisible(true);
    }//GEN-LAST:event_CadastroAActionPerformed
  
    private void CadastroTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroTActionPerformed
        cadastrarTurma cTurma = new cadastrarTurma();
        cTurma.setVisible(true);
    }//GEN-LAST:event_CadastroTActionPerformed

    private void AtribuirTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtribuirTAActionPerformed
        atribuirAlunoTurma aAluno = new atribuirAlunoTurma();
        aAluno.setVisible(true);
    }//GEN-LAST:event_AtribuirTAActionPerformed

    private void CadastroDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroDActionPerformed
        
    }//GEN-LAST:event_CadastroDActionPerformed

    private void CadastroDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroDiscActionPerformed
        cadastrarDisciplina cDisciplina = new cadastrarDisciplina();
        cDisciplina.setVisible(true);
    }//GEN-LAST:event_CadastroDiscActionPerformed

    private void AtribuirTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtribuirTPActionPerformed
         atribuirTurmaProfessor aTProfessor = new atribuirTurmaProfessor();
         aTProfessor.setVisible(true);
    }//GEN-LAST:event_AtribuirTPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AtribuirTA;
    private javax.swing.JMenuItem AtribuirTP;
    private javax.swing.JMenuItem CadastroA;
    private javax.swing.JMenu CadastroD;
    private javax.swing.JMenuItem CadastroDisc;
    private javax.swing.JMenuItem CadastroP;
    private javax.swing.JMenuItem CadastroT;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenuBar menuAdmin;
    private javax.swing.JMenu menuAtribAdmin;
    private javax.swing.JPanel panelAdmin;
    // End of variables declaration//GEN-END:variables
}
